name: prueba
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.17.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
