import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:prueba/typing/dtos/task_dto.dart';
import 'package:prueba/typing/dtos/user_dto.dart';
part 'firebase_data_base_service.dart';
part 'local_data_base.dart';
part 'local_storage_handler.dart';
part 'internet_connection_service.dart';